# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=255)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_user_alt', to='mvc.Usuario'),
        ),
        migrations.AddField(
            model_name='products',
            name='user_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Usuario'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user_alt', to='mvc.Usuario'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Usuario'),
        ),
        migrations.AddField(
            model_name='kart',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Order'),
        ),
        migrations.AddField(
            model_name='kart',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Products'),
        ),
        migrations.AddField(
            model_name='kart',
            name='user_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kart_user_alt', to='mvc.Usuario'),
        ),
        migrations.AddField(
            model_name='kart',
            name='user_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Usuario'),
        ),
    ]
