# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20171206_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dt_cadastro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dt_termino',
        ),
    ]
