# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20171208_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='qtd',
        ),
    ]
