# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_auto_20171206_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dt_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
