# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0004_auto_20171207_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_cadastro',
            field=models.DateField(blank=True),
        ),
    ]
