# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0005_auto_20171207_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_cadastro', models.DateField(blank=True)),
                ('dt_termino', models.DateField(blank=True, null=True)),
                ('id_kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Kart')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_produto', models.CharField(max_length=255)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.AddField(
            model_name='kart',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Products'),
        ),
    ]
