# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0006_auto_20171208_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kart',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_kart',
            new_name='kart',
        ),
    ]
